namespace NekoForms.Utils.Sources
{
    public enum NekosLife
    {
        //Images
        neko,
        avatar,

        //Gifs
        tickle,
        slap,
        pat,
        kiss,
        hug,
        cuddle,
    }

    public enum NekosFun
    {
        //Safe
        kiss,
        lick,
        hug,
        baka,
        cry,
        poke,
        smug,
        slap,
        tickle,
        pat,
        laugh,
        feed,
        cuddle,
        foxgirl,

        //Not safe
        bj,
        boobs,
        cum,
        feet,
        hentai,
        spank,
        gasm,
        lesbian,
        lewd,
        pussy
    }

    public enum HMTaiSafe
    {
        wave,
        wink,
        tea,
        bonk,
        punch,
        poke, 
        bully,
        pat,
        kiss,
        kick,
        blush,
        feed,
        smug,
        hug,
        cuddle,
        cry,
        cringe,
        slap,
        five,
        glomp,
        happy,
        hold,
        nom,
        smile,
        @throw,
        lick,
        bite,
        dance,
        boop,
        sleep,
        like,
        kill,
        tickle,
        nosebleed,
        threaten,
        depression,
        wolfarts,
        jahyarts,
        nekoarts,
        coffeearts,
        wallpaper,
        mobileWallpaper
    }

    public enum HMTaiNotSafe
    {
        ass,
        anal,
        bdsm,
        classic,
        cum,
        creampie,
        manga,
        femdom,
        hentai,
        incest,
        masturbation,
        @public,
        ero,
        orgy,
        elves,
        yuri,
        pantsu,
        pussy,
        glasses,
        cuckold,
        blowjob,
        boobjob,
        handjob,
        footjob,
        boobs,
        thighs,
        ahegao,
        uniform,
        gangbang,
        tentacles,
        gif,
        nsfwNeko,
        nsfwMobileWallpaper,
        zettaiRyouiki,
    }
}